language: python
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
# notifications:
#   email:
#     on_success: change
#     on_failure: always
before_install:
  - pip install codecov
install:
  - pip install ".[test]"
script: pytest --cov=lazyimport
after_success:
  - codecov
